# Generated by Django 4.2.6 on 2023-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccelorometerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='classifiedTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('distance', models.FloatField()),
                ('alignment_Score', models.FloatField()),
                ('long', models.FloatField()),
                ('lati', models.FloatField()),
                ('classified_by', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GyroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('longi', models.FloatField()),
                ('lati', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MagnetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('long', models.FloatField()),
                ('lati', models.FloatField()),
            ],
        ),
    ]
