# Generated by Django 4.2.6 on 2023-10-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollarOneApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='identifyBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100)),
                ('long', models.FloatField()),
                ('lati', models.FloatField()),
                ('behavior', models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='classifiedtemplates',
            name='classified_by',
            field=models.CharField(choices=[('Eucledian_Distance', 'Eucledian_Distance'), ('Alignment_similarity_score', 'Alignment_similarity_score')], max_length=50),
        ),
    ]
