# Generated by Django 4.2.6 on 2023-10-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dollarOneApp', '0002_identifybehaviour_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='identifyBehaviour',
            new_name='identifyBehavior',
        ),
    ]
